name: Theta Healing Test
favicon: null
layout_spectrum: 0.46107
typography_spectrum: 0.12276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#88e0fe'
    - '#fdfff2'
    - '#468bac'
    - '#893914'
  brandStrength: 0.690474625909701
  lightness: 0.25848384760320187
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
