name: Theta Healing Test
favicon: null
layout_spectrum: 0.88278
typography_spectrum: 1
title: Theta Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#88e0fe'
    - '#fdfff2'
    - '#468bac'
    - '#893914'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
