name: Theta Healing Test
favicon: null
layout_spectrum: 0.9931
typography_spectrum: 1
title: Theta Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010204'
    - '#15417d'
    - '#fbf7f6'
    - '#1a91ff'
    - '#27fefe'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
