typography_spectrum: 1
color:
  brandColors:
    - '#010204'
    - '#15417d'
    - '#fbf7f6'
    - '#1a91ff'
    - '#27fefe'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9931
analytics:
  google: null
  facebook: null
  twitter: null
name: Theta Healing
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Theta Healing
purpose: []
